name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

env:
  AZURE_WEBAPP_NAME: tryscape-app    # Set this to your app name
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installation
      run: |
        python verify_installation.py || echo "Verification complete"

    - name: Create deployment artifact
      run: |
        zip -r app.zip . -x ".git/*" ".github/*" "*.pyc" "__pycache__/*" ".venv/*" "venv/*" ".env" "*.log"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: app.zip

    - name: Configure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        app-settings-json: |
          [
            {
              "name": "AZURE_OPENAI_ENDPOINT",
              "value": "${{ secrets.AZURE_OPENAI_ENDPOINT }}",
              "slotSetting": false
            },
            {
              "name": "AZURE_OPENAI_API_KEY",
              "value": "${{ secrets.AZURE_OPENAI_API_KEY }}",
              "slotSetting": false
            },
            {
              "name": "AZURE_OPENAI_DEPLOYMENT_NAME",
              "value": "${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}",
              "slotSetting": false
            },
            {
              "name": "AZURE_OPENAI_API_VERSION",
              "value": "2025-04-01-preview",
              "slotSetting": false
            },
            {
              "name": "FLASK_ENV",
              "value": "production",
              "slotSetting": false
            },
            {
              "name": "FLASK_DEBUG",
              "value": "False",
              "slotSetting": false
            },
            {
              "name": "FLASK_RUN_HOST",
              "value": "0.0.0.0",
              "slotSetting": false
            },
            {
              "name": "FLASK_RUN_PORT",
              "value": "4000",
              "slotSetting": false
            },
            {
              "name": "ENABLE_SORA",
              "value": "false",
              "slotSetting": false
            },
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true",
              "slotSetting": false
            },
            {
              "name": "WEBSITES_PORT",
              "value": "4000",
              "slotSetting": false
            }
          ]

    - name: Azure logout
      run: |
        az logout
